ALTER TABLE "User" ADD COLUMN "omtNumber" TEXT;
ALTER TABLE "Booking" ADD COLUMN "depositAmount" REAL NOT NULL DEFAULT 0;
ALTER TABLE "Booking" ADD COLUMN "paymentMethod" TEXT NOT NULL DEFAULT 'WHISH';
